package sysc3033.group9.elevatorproject.system;

import sysc3033.group9.elevatorproject.GUI.SystemView;
import sysc3033.group9.elevatorproject.constants.Direction;
import sysc3033.group9.elevatorproject.constants.SleepTime;
import sysc3033.group9.elevatorproject.constants.elevator.MotorStatus;
import sysc3033.group9.elevatorproject.elevator.Elevator;
import sysc3033.group9.elevatorproject.elevator.Motor;
import sysc3033.group9.elevatorproject.floor.FloorSpan;
import sysc3033.group9.elevatorproject.util.Sleeper;

/**
 * \
 * 
 * @author Julian Mendoza, Giuseppe Papalia
 *
 */
public class ElevatorSystem implements Runnable {
	private CommunicationPipe pipe;
	private boolean isMoving;
	private int currentFloor;
	private Elevator elevator;
	private SystemView view;

	public ElevatorSystem(FloorSpan floorSpan, CommunicationPipe pipe, SystemView view) {
		this.elevator = new Elevator(floorSpan);
		this.currentFloor = floorSpan.getMinFloorID();
		this.pipe = pipe;
		this.isMoving = false;
		this.view = view;
	}

	@Override
	public void run() {
		while (true) {
			if (pipe.isSchedulerToElevator()) {
				handleElevatorEvent();
			} else if (isMoving) {
				handleMove();
			}
			Sleeper.sleep(SleepTime.DEFAULT);
			view.setQueue(view.getQueueText(), "NONE IN QUEUE");
		}
	}

	private void handleElevatorEvent() {
		/**
		 * TODO if the elevator is not moving, update the motor to go in the
		 * corresponding direction otherwise process the stop generated by the scheduler
		 */
		MotorStatus status = elevator.getMotor().getStatus();
		view.setText(view.getDisplayText(), currentFloor + " " + status + "\n");
		// int floorToMove=pipe.getFloor
		if (status.equals(MotorStatus.IDLE)) {
			// if(currentFloor<)
			System.out.println(Thread.currentThread().getName() + " has received the signal and is currently moving.");
			view.setText(view.getElevatorText(),
					Thread.currentThread().getName() + " has received the signal and is currently moving.\n");
			pipe.setSchedulerToElevator(false);
			isMoving = true;
		}
	}

	private void handleMove() {
		/*
		 * TODO Once the elevator starts moving, it must update the lamps to the
		 * scheduler which will then notify the the floor subsystem
		 */
		Motor elevatorMotor = elevator.getMotor();
		int[] moveEvent = pipe.getNextInQueue();
		view.setQueue(view.getQueueText(), "[ " + moveEvent[0] + " , " + moveEvent[1] + " ]");
		if ((moveEvent[0] - currentFloor) != 0) {
			if ((moveEvent[0] - currentFloor) > 0) {
				elevatorMotor.setStatus(MotorStatus.UP);
				move(Direction.UP, moveEvent[0] - currentFloor);
			} else {
				elevatorMotor.setStatus(MotorStatus.DOWN);
				move(Direction.DOWN, currentFloor - moveEvent[0]);
			}
		}
		if ((moveEvent[1] - currentFloor) > 0) {
			elevatorMotor.setStatus(MotorStatus.UP);
			move(Direction.UP, moveEvent[1] - currentFloor);
		} else {
			elevatorMotor.setStatus(MotorStatus.DOWN);
			move(Direction.DOWN, currentFloor - moveEvent[1]);
		}
		elevatorMotor.setStatus(MotorStatus.IDLE);
		isMoving = false;
	}

	private void move(Direction direction, int steps) {
		for (int i = 0; i < steps; i++) {
			Sleeper.sleep(SleepTime.FLOOR);

			String str = "";
			if (direction.equals(Direction.UP)) {
				currentFloor++;
				str += "The Elevator has moved up to floor " + currentFloor;
			} else {
				currentFloor--;
				str += "The Elevator has moved down to floor " + currentFloor;
			}
			view.setText(view.getDisplayText(), currentFloor + " " + direction + "\n");
			announce(str);
		}
		System.out.println("The Elevator has reached the Floor!");
		System.out.println("Opening the door...");
		view.setText(view.getElevatorText(), "The Elevator has reached the Floor!\nOpening the door...\n");
		Sleeper.sleep(SleepTime.LOAD);
		System.out.println("Closing the door...");
		view.setText(view.getElevatorText(), "DOOR OPENED!\nClosing the door...\n");
		Sleeper.sleep(SleepTime.LOAD);
		view.setText(view.getElevatorText(), "DOOR CLOSED!\n");
	}

	private void announce(String msg) {
		System.out.println(msg);
		view.setText(view.getElevatorText(),
				msg + "\n" + Thread.currentThread().getName() + " has signaled the lamps to the Scheduler.\n");
		System.out.println(Thread.currentThread().getName() + " has signaled the lamps to the Scheduler.");
		pipe.elevatorToFloor();
	}

}
